CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(320) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES app_users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE profile_target_roles (
    profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    role_name VARCHAR(120) NOT NULL,
    PRIMARY KEY (profile_id, sort_order)
);

CREATE TABLE profile_preferred_locations (
    profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    location_name VARCHAR(120) NOT NULL,
    PRIMARY KEY (profile_id, sort_order)
);

CREATE TABLE skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    name VARCHAR(120) NOT NULL,
    normalized_name VARCHAR(120) NOT NULL,
    CONSTRAINT uq_skills_profile_normalized_name UNIQUE (profile_id, normalized_name)
);
CREATE INDEX idx_skills_profile_id ON skills(profile_id);

CREATE TABLE certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    issuer VARCHAR(200),
    acquired_on DATE
);
CREATE INDEX idx_certificates_profile_id ON certificates(profile_id);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    tech_stack TEXT,
    started_on DATE,
    ended_on DATE,
    project_url VARCHAR(1000),
    CONSTRAINT ck_projects_dates CHECK (ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on)
);
CREATE INDEX idx_projects_profile_id ON projects(profile_id);

CREATE TABLE experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
    company_name VARCHAR(200) NOT NULL,
    role_name VARCHAR(200) NOT NULL,
    description TEXT,
    started_on DATE NOT NULL,
    ended_on DATE,
    CONSTRAINT ck_experiences_dates CHECK (ended_on IS NULL OR ended_on >= started_on)
);
CREATE INDEX idx_experiences_profile_id ON experiences(profile_id);

CREATE TABLE job_postings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(200) NOT NULL,
    title VARCHAR(200) NOT NULL,
    role_name VARCHAR(120) NOT NULL,
    company_type VARCHAR(100),
    career_level VARCHAR(100),
    description TEXT,
    responsibilities TEXT NOT NULL,
    location VARCHAR(200) NOT NULL,
    deadline DATE,
    status VARCHAR(16) NOT NULL,
    source_url VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_job_postings_status CHECK (status IN ('DRAFT', 'OPEN', 'CLOSED', 'EXPIRED'))
);
CREATE INDEX idx_job_postings_status_deadline ON job_postings(status, deadline);

CREATE TABLE job_required_skills (
    job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    skill_name VARCHAR(120) NOT NULL,
    PRIMARY KEY (job_id, sort_order)
);

CREATE TABLE job_preferred_skills (
    job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    skill_name VARCHAR(120) NOT NULL,
    PRIMARY KEY (job_id, sort_order)
);

CREATE TABLE recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    job_id BIGINT NOT NULL REFERENCES job_postings(id),
    total_score NUMERIC(5, 2) NOT NULL,
    required_score NUMERIC(5, 2) NOT NULL,
    preferred_score NUMERIC(5, 2) NOT NULL,
    semantic_score NUMERIC(5, 2) NOT NULL,
    experience_score NUMERIC(5, 2) NOT NULL,
    preference_score NUMERIC(5, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_recommendations_total_score CHECK (total_score BETWEEN 0 AND 100),
    CONSTRAINT ck_recommendations_required_score CHECK (required_score BETWEEN 0 AND 100),
    CONSTRAINT ck_recommendations_preferred_score CHECK (preferred_score BETWEEN 0 AND 100),
    CONSTRAINT ck_recommendations_semantic_score CHECK (semantic_score BETWEEN 0 AND 100),
    CONSTRAINT ck_recommendations_experience_score CHECK (experience_score BETWEEN 0 AND 100),
    CONSTRAINT ck_recommendations_preference_score CHECK (preference_score BETWEEN 0 AND 100)
);
CREATE INDEX idx_recommendations_user_created_at ON recommendations(user_id, created_at DESC);
CREATE INDEX idx_recommendations_job_id ON recommendations(job_id);

CREATE TABLE recommendation_evidence (
    recommendation_id BIGINT NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    evidence_text TEXT NOT NULL,
    PRIMARY KEY (recommendation_id, sort_order)
);

CREATE TABLE recommendation_missing_skills (
    recommendation_id BIGINT NOT NULL REFERENCES recommendations(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL,
    skill_name VARCHAR(120) NOT NULL,
    PRIMARY KEY (recommendation_id, sort_order)
);
