ALTER TABLE job_postings ADD COLUMN origin VARCHAR(16) NOT NULL DEFAULT 'LEGACY';
ALTER TABLE job_postings ADD COLUMN source_name VARCHAR(80);
ALTER TABLE job_postings ADD COLUMN external_id VARCHAR(200);
ALTER TABLE job_postings ADD COLUMN collected_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE job_postings ADD COLUMN last_seen_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE job_postings ADD COLUMN content_hash VARCHAR(64);
UPDATE job_postings SET origin = 'SYNTHETIC' WHERE seed_key IS NOT NULL;
ALTER TABLE job_postings ADD CONSTRAINT ck_job_origin CHECK (origin IN ('SYNTHETIC', 'REAL', 'LEGACY'));
ALTER TABLE job_postings ADD CONSTRAINT uq_job_source_external UNIQUE (source_name, external_id);
ALTER TABLE job_postings ADD CONSTRAINT ck_real_job_source CHECK
    (origin <> 'REAL' OR (source_name IS NOT NULL AND external_id IS NOT NULL AND source_url IS NOT NULL
                         AND collected_at IS NOT NULL AND last_seen_at IS NOT NULL AND content_hash IS NOT NULL));

CREATE TABLE job_source_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    snapshot_json TEXT NOT NULL,
    terms_url VARCHAR(1000) NOT NULL,
    permission_evidence VARCHAR(2000) NOT NULL,
    policy_reviewed_on DATE NOT NULL
);
CREATE INDEX idx_job_source_revision_job ON job_source_revisions(job_id, id);
